Repository rrajpuro/DollarBot, pull requests merged in 2023-10, with the labels that each got.

#2 Updating CONTRIBUTING.md with latest info
  CONTRIBUTING.md
Labels: documentation

#4 Decouples variables from helper.py. Fixes #3
  code/add.py
  code/code.py
  code/helper.py
  variables.json
Labels: enhancement

#9 Create styleChecker.yml
  .flake8
  .github/workflows/styleChecker.yml
  code/add.py
  code/add_recurring.py
  code/category.py
  code/code.py
  code/display.py
  code/graphing.py
  code/helper.py
  code/history.py
  test/test_add.py
  test/test_add_recurring.py
  test/test_budget.py
  test/test_budget_update_rest.py
  test/test_budget_update_run.py
  test/test_budget_view.py
  test/test_category.py
  test/test_delete.py
  test/test_graph.py
  test/test_helper.py
  test/test_history.py
Labels: enhancement

#13 Updating the Readme file.
  README.md
Labels: documentation

#15 Update to the Readme Badges
  README.md
Labels: documentation

#14 Create testCases.yml
  .github/workflows/testCases.yml
  requirements.txt
  test/test_add.py
  test/test_add_recurring.py
  test/test_budget.py
  test/test_budget_view.py
  test/test_category.py
Labels: enhancement, new feature

#23 Update .flake8
  .flake8
  test/test_display.py
Labels: bug

#29 Bugfix/setreminder nohistory
  code/code.py
  code/display.py
  code/estimate.py
  code/reminder.py
Labels: bug

#34 Updated the README.md
  README.md
Labels: documentation
